#!/bin/bash
# Build on macOS or Linux using Bash 3.2 and standard utilities.
set -eu
set -o pipefail
cd "$(dirname "$0")/.."
export LC_ALL=C
project_root=$(pwd -P)

fail() { printf 'Build error: %s\n' "$*" >&2; exit 1; }
safe_path() {
  case "$1" in ''|/*|*/|*//*|.|..|./*|../*|*/./*|*/../*|*/.|*/..) return 1 ;; esac
  [[ "$1" =~ ^[a-zA-Z0-9._/-]+$ ]]
}

command -v realpath >/dev/null 2>&1 || fail 'realpath is required on the build machine'
temp_base=${TMPDIR:-/tmp}
build_tmp=$(mktemp -d "${temp_base%/}/codex-dotfiles-build.XXXXXX")
touch "$build_tmp/.codex-task-temp"
: > "$build_tmp/manifest.tsv"
# Build output cleanup uses canonical paths and ownership sentinels.
temp_root=$(realpath "$temp_base")
codex_root=${CODEX_HOME:-$HOME/.codex}
if [ -d "$codex_root" ]; then codex_root=$(realpath "$codex_root"); fi
remove_generated() {
  local cleanup_target=$1 kind=$2
  [ -n "$cleanup_target" ] || fail 'Empty cleanup target'
  cleanup_target=$(realpath "$cleanup_target")
  case "$cleanup_target" in
    /|"$(realpath "$HOME")"|"$codex_root"|"$temp_root"|"$project_root")
      fail "Protected cleanup target: $cleanup_target" ;;
  esac
  case "$kind" in
    temp)
      [ "$(dirname "$cleanup_target")" = "$temp_root" ] || fail 'Unexpected temporary directory'
      case "$(basename "$cleanup_target")" in codex-dotfiles-build.*) ;; *) fail 'Unexpected temporary prefix' ;; esac
      [ -f "$cleanup_target/.codex-task-temp" ] || fail 'Missing temporary sentinel'
      ;;
    dist)
      [ "$cleanup_target" = "$project_root/dist" ] && [ -f "$cleanup_target/.dotfiles-generated" ] || fail 'dist is not a recognized generated directory'
      ;;
    *) fail 'Unknown cleanup kind' ;;
  esac
  /bin/rm -rf "$cleanup_target"
}
cleanup() {
  remove_generated "$build_tmp" temp
}
trap cleanup EXIT

ids='|'
revision_sources=(scripts/build.sh installer/install.sh installer/restore.sh installer/manifest.tsv)
while IFS=$'\t' read -r id source destination validator minimum extra || [ -n "$id" ]; do
  case "$id" in ''|\#*) continue ;; esac
  [[ "$id" =~ ^[a-zA-Z0-9_-]+$ ]] || fail "Invalid id: $id"
  if ! safe_path "$source" || ! safe_path "$destination"; then fail "Invalid path for $id"; fi
  [ -z "$extra" ] && [ -n "$minimum" ] || fail "Expected five tab-separated fields for $id"
  case "$ids" in *"|$id|"*) fail "Duplicate id: $id" ;; esac
  # Prevent destinations from being equal or nesting inside each other.
  while IFS=$'\t' read -r _previous_id _previous_source previous_destination _rest; do
    case "$destination/" in "$previous_destination/"*) fail "Overlapping destinations: $destination" ;; esac
    case "$previous_destination/" in "$destination/"*) fail "Overlapping destinations: $destination" ;; esac
  done < "$build_tmp/manifest.tsv"
  case "$destination" in .dotfiles-backups|.dotfiles-backups/*) fail 'Reserved backup path' ;; esac
  case "$validator" in
    vim|tmux) [[ "$minimum" =~ ^[0-9]+\.[0-9]+$ ]] || fail "Invalid minimum version for $id" ;;
    none) [ "$minimum" = '-' ] || fail 'Use - for the minimum with validator none' ;;
    *) fail "Unknown validator: $validator" ;;
  esac
  [ -f "$source" ] && [ ! -L "$source" ] || fail "Not a regular source file: $source"
  # Quoted heredocs represent text files exactly when they end in a newline.
  [ ! -s "$source" ] || [ -z "$(tail -c 1 "$source")" ] || fail "$source must end in a newline"
  [ "$(tr -d '\000' < "$source" | wc -c)" -eq "$(wc -c < "$source")" ] || fail "$source contains NUL bytes"
  ids="$ids$id|"
  revision_sources+=("$source")
  printf '%s\t%s\t%s\t%s\t%s\n' "$id" "$source" "$destination" "$validator" "$minimum" >> "$build_tmp/manifest.tsv"
done < installer/manifest.tsv
[ -s "$build_tmp/manifest.tsv" ] || fail 'Manifest contains no files'

revision=$(git rev-parse --short=12 HEAD 2>/dev/null || printf unknown)
# Netlify may create unrelated build-service files in the checkout. Only input
# files that contribute to this installer should affect its dirty suffix.
if [ -n "$(git status --porcelain --untracked-files=all -- "${revision_sources[@]}" 2>/dev/null)" ]; then revision="$revision-dirty"; fi

emit_file() {
  local input=$1 marker=$2
  if grep -Fxq "$marker" "$input"; then fail "Heredoc marker collision: $input"; fi
  printf "cat <<'%s'\n" "$marker"
  cat "$input"
  printf '%s\n' "$marker"
}

{
  printf '#!/bin/bash\n# Generated by scripts/build.sh; edit source files instead.\n'
  printf 'DOTFILES_REVISION=%q\n' "$revision"
  cat installer/install.sh
  printf '\nwrite_manifest() {\n'
  emit_file "$build_tmp/manifest.tsv" DOTFILES_MANIFEST_END
  printf '}\n\nwrite_restore() {\n'
  emit_file installer/restore.sh DOTFILES_RESTORE_END
  # shellcheck disable=SC2016 # This is generated shell source.
  printf '}\n\nwrite_payload() {\ncase "$1" in\n'
  while IFS=$'\t' read -r id source destination validator minimum; do
    printf '%s)\n' "$id"
    emit_file "$source" "DOTFILES_PAYLOAD_${id}_END"
    printf ';;\n'
  done < "$build_tmp/manifest.tsv"
  printf '*) return 1 ;;\nesac\n}\n'
  # No installation work runs until Bash has read every payload and this footer.
  printf '\n# Complete payload received.\nmain "$@"\n'
} > "$build_tmp/install.sh"
/bin/bash -n "$build_tmp/install.sh"

[ ! -L dist ] || fail 'dist must not be a symlink'
mkdir "$build_tmp/site"
touch "$build_tmp/site/.dotfiles-generated"
cp "$build_tmp/install.sh" "$build_tmp/site/install.sh"
chmod 644 "$build_tmp/site/install.sh"
# Keep the /web/ namespace. Publish tracked assets only: no ignored local files.
git ls-files -z -- web/ > "$build_tmp/web-assets"
while IFS= read -r -d '' asset; do
  safe_path "$asset" || fail "Invalid web asset path: $asset"
  [ -f "$asset" ] && [ ! -L "$asset" ] || fail "Not a regular web asset: $asset"
  asset_parent=$(dirname "$build_tmp/site/$asset")
  mkdir -p "$asset_parent"
  cp "$asset" "$build_tmp/site/$asset"
done < "$build_tmp/web-assets"
if [ -e dist ]; then remove_generated "$project_root/dist" dist; fi
mv "$build_tmp/site" dist
printf 'Built dist/install.sh (%s); copied tracked web/ assets.\n' "$revision"
